import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

import { selectCanonicalSkillNames } from "./skillSelector.js";

const defaultRepositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
);

const generatedArtifacts = [
  {
    entryPoint: "./src/committing-to-git/cli/commitWorkflow.js",
    outputFile: "skills/committing-to-git/scripts/commitWorkflow.mjs",
    skillName: "committing-to-git",
  },
];

async function generateArtifact(definition, repositoryRoot) {
  const result = await build({
    absWorkingDir: repositoryRoot,
    entryPoints: [resolve(repositoryRoot, definition.entryPoint)],
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node22",
    minify: false,
    sourcemap: false,
    legalComments: "inline",
    write: false,
    banner: {
      js: [
        "// Generated by scripts/buildSkillArtifacts.js. Edit src/, then run npm run build.",
        'import { createRequire as __createRequire } from "node:module";',
        "const require = __createRequire(import.meta.url);",
      ].join("\n"),
    },
  });

  if (result.outputFiles.length !== 1) {
    throw new Error(
      `${definition.entryPoint} produced ${result.outputFiles.length} outputs; expected one.`,
    );
  }

  return result.outputFiles[0].text;
}

export async function buildSkillArtifacts({
  checkOnly = false,
  repositoryRoot = defaultRepositoryRoot,
  skillNames,
} = {}) {
  const resolvedRepositoryRoot = resolve(repositoryRoot);
  const selectedSkillNames =
    skillNames === undefined
      ? undefined
      : selectCanonicalSkillNames(
          resolve(resolvedRepositoryRoot, "skills"),
          skillNames,
        );
  const selectedArtifacts =
    selectedSkillNames === undefined
      ? generatedArtifacts
      : generatedArtifacts.filter((definition) =>
          selectedSkillNames.includes(definition.skillName),
        );
  const staleArtifacts = [];

  for (const definition of selectedArtifacts) {
    const outputPath = resolve(resolvedRepositoryRoot, definition.outputFile);
    const generated = await generateArtifact(
      definition,
      resolvedRepositoryRoot,
    );

    if (checkOnly) {
      let committed;

      try {
        committed = readFileSync(outputPath, "utf8");
      } catch (error) {
        if (error.code !== "ENOENT") {
          throw error;
        }
      }

      if (committed !== generated) {
        staleArtifacts.push(definition.outputFile);
      }
    } else {
      writeFileSync(outputPath, generated);
      process.stdout.write(`Built ${definition.outputFile}\n`);
    }
  }

  return {
    artifactsChecked: selectedArtifacts.length,
    staleArtifacts,
  };
}
