import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

import { build } from "esbuild";

import { selectCanonicalSkillNames } from "./skillSelector.js";
import {
  authoredRuntimeFiles,
  regularFileInventory,
  assertUnredirectedPath,
} from "./skillDistribution.js";
import { compileSuite } from "./evaluation/compile-suite.js";
import { validateCanonicalSkillAscii } from "./validateSkillRepository.js";

const defaultRepositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
);

const generatedArtifacts = [
  {
    entryPoint: "./src/committing-to-git/cli/commitWorkflow.js",
    outputFile: "skills/committing-to-git/scripts/commitWorkflow.mjs",
    skillName: "committing-to-git",
  },
];

async function generateArtifact(definition, repositoryRoot) {
  const result = await build({
    absWorkingDir: repositoryRoot,
    entryPoints: [resolve(repositoryRoot, definition.entryPoint)],
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node22",
    minify: false,
    sourcemap: false,
    legalComments: "inline",
    write: false,
    banner: {
      js: [
        "// Generated by scripts/buildSkillArtifacts.js. Edit src/, then run npm run build.",
        'import { createRequire as __createRequire } from "node:module";',
        "const require = __createRequire(import.meta.url);",
      ].join("\n"),
    },
  });

  if (result.outputFiles.length !== 1) {
    throw new Error(
      `${definition.entryPoint} produced ${result.outputFiles.length} outputs; expected one.`,
    );
  }

  return result.outputFiles[0].text;
}

export async function buildSkillArtifacts({
  checkOnly = false,
  repositoryRoot = defaultRepositoryRoot,
  skillNames,
} = {}) {
  const resolvedRepositoryRoot = resolve(repositoryRoot);
  const selectedSkillNames = selectCanonicalSkillNames(
    resolve(resolvedRepositoryRoot, "src"),
    skillNames,
  );
  const selectedArtifacts = generatedArtifacts.filter((definition) =>
    selectedSkillNames.includes(definition.skillName),
  );
  const staleArtifacts = [];
  const intended = new Map(
    selectedSkillNames.map((name) => [
      name,
      authoredRuntimeFiles(resolvedRepositoryRoot, name),
    ]),
  );

  for (const definition of selectedArtifacts) {
    const generated = await generateArtifact(
      definition,
      resolvedRepositoryRoot,
    );

    const relativePath = definition.outputFile.slice(
      `skills/${definition.skillName}/`.length,
    );
    if (intended.get(definition.skillName).has(relativePath))
      throw new Error(`Conflicting runtime output: ${definition.outputFile}`);
    intended
      .get(definition.skillName)
      .set(relativePath, Buffer.from(generated));
  }

  // Validate the complete candidate before any output mutation, including clean
  // first builds. Unexpected files need disposition and are never purged.
  for (const [skillName, files] of intended) {
    compileSuite({
      repositoryRoot: resolvedRepositoryRoot,
      skillName,
      distributionFiles: files,
    });
    const directory = resolve(resolvedRepositoryRoot, "skills", skillName);
    assertUnredirectedPath(directory);
    if (existsSync(resolve(directory, "SKILL.md")))
      validateCanonicalSkillAscii(directory);
    if (existsSync(directory))
      for (const file of regularFileInventory(directory).keys()) {
        if (!files.has(file))
          throw new Error(
            `Unexpected runtime output requires disposition: skills/${skillName}/${file}`,
          );
      }
  }
  // Preflight all existing destinations before writing any candidate output.
  if (!checkOnly)
    for (const [skillName, files] of intended)
      for (const [relativePath, bytes] of files) {
        const outputFile = `skills/${skillName}/${relativePath}`;
        const outputPath = resolve(resolvedRepositoryRoot, outputFile);
        assertUnredirectedPath(outputPath);
        if (!existsSync(outputPath) || readFileSync(outputPath).equals(bytes))
          continue;
        const committed = spawnSync("git", ["show", `HEAD:${outputFile}`], {
          cwd: resolvedRepositoryRoot,
          windowsHide: true,
          maxBuffer: 16 * 1024 * 1024,
        });
        if (
          committed.status === 0 &&
          !readFileSync(outputPath).equals(committed.stdout)
        )
          throw new Error(
            `Locally modified runtime output requires disposition: ${outputFile}`,
          );
      }
  for (const [skillName, files] of intended)
    for (const [relativePath, bytes] of files) {
      const outputFile = `skills/${skillName}/${relativePath}`;
      const outputPath = resolve(resolvedRepositoryRoot, outputFile);
      const committed = existsSync(outputPath)
        ? readFileSync(outputPath)
        : undefined;
      if (committed?.equals(bytes)) continue;
      if (checkOnly) staleArtifacts.push(outputFile);
      else {
        mkdirSync(dirname(outputPath), { recursive: true });
        writeFileSync(outputPath, bytes);
        process.stdout.write(`Built ${outputFile}\n`);
      }
    }

  return {
    artifactsChecked: [...intended.values()].reduce(
      (count, files) => count + files.size,
      0,
    ),
    staleArtifacts,
  };
}
