import { createHash } from "node:crypto";
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { selectCanonicalSkillNames } from "./skillSelector.js";

const defaultRepositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
);

// Every host plugin is generated from the canonical skill it packages, never
// edited in place. A plugin directory must be self-contained: a marketplace
// `git-subdir` source sparse-clones only that path, so the skill files are
// copied in rather than referenced.
const pluginPackages = [
  {
    skillName: "committing-to-git",
    outputDirectory: "plugins/committing-to-git",
    identity: {
      name: "committing-to-git",
      description:
        "Prepare commit messages, create signed commits, verify results and publish authorized commits.",
      author: { name: "Hadden Industries Ltd" },
      license: "MPL-2.0",
      repository: "https://github.com/Hadden-Industries/agent-skills",
    },
    codexInterface: {
      displayName: "Committing to Git",
      shortDescription: "Prepare and verify authorized signed Git commits.",
      developerName: "Hadden Industries Ltd",
      category: "Developer Tools",
      capabilities: [],
      defaultPrompt: ["Prepare a commit for my changes."],
    },
    // Third-party code bundled into the published helper executable; each
    // package's licence text ships beside it.
    bundledDependencies: [
      "cross-spawn",
      "isexe",
      "path-key",
      "shebang-command",
      "shebang-regex",
      "which",
    ],
    readme: [
      "# Committing to Git",
      "",
      "Generated by `npm run build` from the canonical `skills/committing-to-git` in",
      "https://github.com/Hadden-Industries/agent-skills. Edit the canonical skill and",
      "helper there; this directory is a host plugin package of that skill and carries",
      "no other changes.",
      "",
      "Install it through a marketplace entry that points at this directory, pinned to",
      "an exact commit, or extract the release archive for hosts without a marketplace.",
      "",
      "Owner-authored code is MPL-2.0; the licences of third-party code bundled into",
      "the helper executable are in `notices/`. The complete corresponding source, build",
      "and tests are in the repository above (`npm ci`, then `npm run build`).",
      "",
    ].join("\n"),
  },
];

function json(value) {
  return Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
}

function collectFiles(directory, prefix, files) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    const published = `${prefix}/${entry.name}`;

    if (entry.isDirectory()) {
      collectFiles(path, published, files);
    } else if (entry.isFile()) {
      files.set(published, readFileSync(path));
    } else {
      throw new Error(`Unsupported plugin input: ${path}`);
    }
  }
}

function licenceNotice(repositoryRoot, packageName) {
  const directory = join(repositoryRoot, "node_modules", packageName);
  const notices = readdirSync(directory, { withFileTypes: true }).filter(
    (entry) => entry.isFile() && /^licen[cs]e(\.md|\.txt)?$/iu.test(entry.name),
  );

  if (notices.length !== 1) {
    throw new Error(
      `Expected exactly one licence file for ${packageName}; found ${notices.length}.`,
    );
  }

  return readFileSync(join(directory, notices[0].name));
}

// The manifest version is derived from every published byte except the
// manifests' own version fields, so hosts that cache plugins by version
// (Claude Code does) fetch a new copy exactly when the shipped skill changes,
// and an unchanged skill keeps its version across rebuilds.
function contentVersion(files, manifests) {
  const digest = createHash("sha256");
  const entries = [...files, ...manifests].sort(([left], [right]) =>
    left.localeCompare(right, "en"),
  );

  for (const [path, bytes] of entries) {
    digest.update(
      JSON.stringify([path, createHash("sha256").update(bytes).digest("hex")]),
    );
  }

  return `0.1.0-dev.g${digest.digest("hex").slice(0, 16)}`;
}

export function pluginPackageFiles(definition, repositoryRoot) {
  const files = new Map();

  collectFiles(
    join(repositoryRoot, "skills", definition.skillName),
    `skills/${definition.skillName}`,
    files,
  );
  files.set("LICENSE", readFileSync(join(repositoryRoot, "LICENSE")));

  for (const packageName of definition.bundledDependencies) {
    files.set(
      `notices/${packageName}.LICENSE`,
      licenceNotice(repositoryRoot, packageName),
    );
  }

  files.set("README.md", Buffer.from(definition.readme));

  const codexManifest = (manifest) => ({
    ...manifest,
    skills: "./skills/",
    interface: {
      ...definition.codexInterface,
      longDescription: manifest.description,
    },
  });
  const version = contentVersion(files, [
    [".claude-plugin/plugin.json", json(definition.identity)],
    [".codex-plugin/plugin.json", json(codexManifest(definition.identity))],
  ]);
  const manifest = { ...definition.identity, version };

  files.set(".claude-plugin/plugin.json", json(manifest));
  files.set(".codex-plugin/plugin.json", json(codexManifest(manifest)));

  return { files, manifest };
}

function existingFiles(directory, prefix, paths) {
  let entries;

  try {
    entries = readdirSync(directory, { withFileTypes: true });
  } catch (error) {
    if (error.code === "ENOENT") {
      return;
    }

    throw error;
  }

  for (const entry of entries) {
    const published = prefix ? `${prefix}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      existingFiles(join(directory, entry.name), published, paths);
    } else {
      paths.push(published);
    }
  }
}

function syncPackage(definition, repositoryRoot, checkOnly) {
  const outputRoot = resolve(repositoryRoot, definition.outputDirectory);
  const { files } = pluginPackageFiles(definition, repositoryRoot);
  const stale = [];
  const published = [];

  existingFiles(outputRoot, "", published);

  for (const path of published) {
    if (!files.has(path)) {
      stale.push(`${definition.outputDirectory}/${path}`);

      if (!checkOnly) {
        rmSync(join(outputRoot, path));
      }
    }
  }

  for (const [path, expected] of files) {
    const destination = join(outputRoot, path);
    let committed;

    try {
      committed = readFileSync(destination);
    } catch (error) {
      if (error.code !== "ENOENT") {
        throw error;
      }
    }

    if (!committed?.equals(expected)) {
      stale.push(`${definition.outputDirectory}/${path}`);

      if (!checkOnly) {
        mkdirSync(dirname(destination), { recursive: true });
        writeFileSync(destination, expected);
      }
    }
  }

  return stale;
}

export function pluginPackageDefinition(skillName) {
  const definition = pluginPackages.find(
    (candidate) => candidate.skillName === skillName,
  );

  if (!definition) {
    throw new Error(`No host plugin package is generated for ${skillName}.`);
  }

  return definition;
}

export function buildPluginPackages({
  checkOnly = false,
  repositoryRoot = defaultRepositoryRoot,
  skillNames,
} = {}) {
  const resolvedRepositoryRoot = resolve(repositoryRoot);
  const selectedSkillNames =
    skillNames === undefined
      ? undefined
      : selectCanonicalSkillNames(
          resolve(resolvedRepositoryRoot, "skills"),
          skillNames,
        );
  const selected =
    selectedSkillNames === undefined
      ? pluginPackages
      : pluginPackages.filter((definition) =>
          selectedSkillNames.includes(definition.skillName),
        );
  const stalePackages = [];

  for (const definition of selected) {
    // In write mode every difference has just been synchronised, so only a
    // check reports them as stale.
    const changed = syncPackage(definition, resolvedRepositoryRoot, checkOnly);

    if (checkOnly) {
      stalePackages.push(...changed);
    } else {
      process.stdout.write(
        `Built ${definition.outputDirectory} (${changed.length} file(s) changed)\n`,
      );
    }
  }

  return { packagesChecked: selected.length, stalePackages };
}
