import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { parseArgs } from "node:util";

import { isMap, isScalar, parseDocument } from "yaml";

import { selectCanonicalSkillNames } from "./skillSelector.js";
import { readStableFile } from "../lib/filesystem/stableFile.js";
import { replaceReleaseFile } from "./releaseFile.js";
import { assertUnredirectedPath } from "./skillDistribution.js";
import {
  packageInputSha256,
  readReleaseLedger,
  releaseLedgerPath,
  validateReleaseLedger,
} from "./pluginRelease.js";

const defaultRepositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
);

// Every host plugin is generated from the canonical skill it packages, never
// edited in place. A plugin directory must be self-contained: a marketplace
// `git-subdir` source sparse-clones only that path, so the skill files are
// copied in rather than referenced.
const pluginPackages = [
  {
    skillName: "committing-to-git",
    outputDirectory: "plugins/committing-to-git",
    identity: {
      name: "committing-to-git",
      description:
        "Prepare commit messages, create signed commits, verify results and publish authorized commits.",
      author: { name: "Hadden Industries Ltd" },
      license: "MPL-2.0",
      repository: "https://github.com/Hadden-Industries/agent-skills",
    },
    codexInterface: {
      displayName: "Committing to Git",
      shortDescription: "Prepare and verify authorized signed Git commits.",
      developerName: "Hadden Industries Ltd",
      category: "Developer Tools",
      capabilities: [],
      defaultPrompt: ["Prepare a commit for my changes."],
    },
    // Third-party code bundled into the published helper executable; each
    // package's licence text ships beside it.
    bundledDependencies: [
      "cross-spawn",
      "isexe",
      "path-key",
      "shebang-command",
      "shebang-regex",
      "which",
    ],
    readme: [
      "# Committing to Git",
      "",
      "Generated by `npm run build` from `skills/committing-to-git`, authored in `src/committing-to-git`, in",
      "https://github.com/Hadden-Industries/agent-skills. Edit the canonical skill and",
      "helper there; this directory is a host plugin package of that skill and carries",
      "no other changes.",
      "",
      "Install it through a marketplace entry that points at this directory, pinned to",
      "an exact commit, or extract the release archive for hosts without a marketplace.",
      "",
      "Owner-authored code is MPL-2.0; the licences of third-party code bundled into",
      "the helper executable are in `notices/`. The complete corresponding source, build",
      "and tests are in the repository above (`npm ci`, then `npm run build`).",
      "",
    ].join("\n"),
  },
];

function json(value) {
  return Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
}

function collectFiles(directory, prefix, files) {
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    const published = `${prefix}/${entry.name}`;

    if (entry.isDirectory()) {
      collectFiles(path, published, files);
    } else if (entry.isFile()) {
      files.set(published, readFileSync(path));
    } else {
      throw new Error(`Unsupported plugin input: ${path}`);
    }
  }
}

function licenceNotice(repositoryRoot, packageName) {
  const directory = join(repositoryRoot, "node_modules", packageName);
  const notices = readdirSync(directory, { withFileTypes: true }).filter(
    (entry) => entry.isFile() && /^licen[cs]e(\.md|\.txt)?$/iu.test(entry.name),
  );

  if (notices.length !== 1) {
    throw new Error(
      `Expected exactly one licence file for ${packageName}; found ${notices.length}.`,
    );
  }

  return readFileSync(join(directory, notices[0].name));
}

function pluginPackageInputs(definition, repositoryRoot) {
  const files = new Map();

  collectFiles(
    join(repositoryRoot, "skills", definition.skillName),
    `skills/${definition.skillName}`,
    files,
  );
  files.set("LICENSE", readFileSync(join(repositoryRoot, "LICENSE")));

  for (const packageName of definition.bundledDependencies) {
    files.set(
      `notices/${packageName}.LICENSE`,
      licenceNotice(repositoryRoot, packageName),
    );
  }

  files.set("README.md", Buffer.from(definition.readme));

  const codexManifest = (manifest) => ({
    ...manifest,
    skills: "./skills/",
    interface: {
      ...definition.codexInterface,
      longDescription: manifest.description,
    },
  });
  const contentSha256 = packageInputSha256(files, [
    [".claude-plugin/plugin.json", json(definition.identity)],
    [".codex-plugin/plugin.json", json(codexManifest(definition.identity))],
  ]);
  return { files, codexManifest, contentSha256 };
}

function skillFrontmatter(text) {
  const match = /^---\n([\s\S]*?\n)---(?:\n|$)/u.exec(text);
  if (!match) throw new Error("SKILL.md requires LF YAML frontmatter.");
  const document = parseDocument(match[1], { uniqueKeys: true });
  if (document.errors.length) throw new Error(document.errors[0].message);
  return { document, frontmatter: match[1] };
}

// SKILL.md is itself distributed identity, so it must agree before the digest
// is checked. The normal build only validates; it never assigns a version.
export function pluginPackageFiles(definition, repositoryRoot) {
  const { files, codexManifest, contentSha256 } = pluginPackageInputs(
    definition,
    repositoryRoot,
  );
  const releases =
    readReleaseLedger(repositoryRoot).plugins[definition.skillName];
  const release = releases?.at(-1);
  const { document } = skillFrontmatter(
    files.get(`skills/${definition.skillName}/SKILL.md`).toString("utf8"),
  );
  if (document.getIn(["metadata", "version"]) !== release?.version) {
    throw new Error(
      `${definition.skillName} SKILL.md metadata.version must agree with the selected release version.`,
    );
  }
  if (!release || release.contentSha256 !== contentSha256) {
    throw new Error(
      `${definition.skillName} published inputs changed (${contentSha256}); deliberately advance the release with buildPluginPackages.js --release-version <next-version>.`,
    );
  }
  const { version } = release;
  const manifest = { ...definition.identity, version };

  files.set(".claude-plugin/plugin.json", json(manifest));
  files.set(".codex-plugin/plugin.json", json(codexManifest(manifest)));

  return { files, manifest, contentSha256 };
}

// One deliberate operation updates the canonical identity and invokes the same
// generators as npm run build. Failures preserve intermediate files for review;
// ordinary build/check will reject an incomplete release, never auto-advance it.
export async function advancePluginRelease({
  version,
  repositoryRoot = defaultRepositoryRoot,
}) {
  const root = resolve(repositoryRoot);
  const definition = pluginPackageDefinition("committing-to-git");
  const ledgerPath = join(root, releaseLedgerPath);
  const ledgerSnapshot = readStableFile(ledgerPath, 32 * 1024 * 1024, {
    rejectLinkedAncestors: true,
  });
  const previous = readReleaseLedger(root, ledgerSnapshot.bytes);
  const ledger = structuredClone(previous);
  const releases = ledger.plugins[definition.skillName];
  releases.push({ version, contentSha256: "0".repeat(64) });
  // Reject invalid/repeated/backwards versions before changing any files.
  validateReleaseLedger(ledger, previous);
  const sourcePath = join(root, "src", definition.skillName, "SKILL.md");
  // Preserve the author-facing linked-path diagnostic; descriptor validation
  // below, rather than this preliminary path check, establishes read safety.
  assertUnredirectedPath(sourcePath);
  const sourceSnapshot = readStableFile(sourcePath, 32 * 1024 * 1024, {
    rejectLinkedAncestors: true,
  });
  const text = sourceSnapshot.bytes.toString("utf8");
  const { document, frontmatter } = skillFrontmatter(text);
  const metadata = document.get("metadata", true);
  if (!isMap(metadata) || metadata.flow)
    throw new Error("Canonical metadata must be a YAML block mapping.");
  const existing = metadata.get("version", true);
  if (existing && (!isScalar(existing) || typeof existing.value !== "string"))
    throw new Error("Canonical metadata.version must be a string scalar.");
  // Block scalar ranges include their final newline and header comments; a
  // release number belongs in an inline scalar, so refuse before writing.
  if (["BLOCK_FOLDED", "BLOCK_LITERAL"].includes(existing?.type))
    throw new Error(
      "Canonical metadata.version cannot use a block string scalar.",
    );
  // Native YAML node ranges keep descriptions, comments and body bytes intact.
  const start = existing?.range[0] ?? metadata.range[1];
  const end = existing?.range[1] ?? start;
  const replacement = existing
    ? JSON.stringify(version)
    : `  version: ${JSON.stringify(version)}\n`;
  const updated =
    frontmatter.slice(0, start) + replacement + frontmatter.slice(end);
  replaceReleaseFile(
    sourcePath,
    sourceSnapshot,
    Buffer.from(`---\n${updated}${text.slice(4 + frontmatter.length)}`),
  );
  const { buildSkillArtifacts } = await import("./buildSkillArtifacts.js");
  await buildSkillArtifacts({
    repositoryRoot: root,
    skillNames: [definition.skillName],
  });
  releases.at(-1).contentSha256 = pluginPackageInputs(
    definition,
    root,
  ).contentSha256;
  validateReleaseLedger(ledger, previous);
  replaceReleaseFile(ledgerPath, ledgerSnapshot, json(ledger));
  buildPluginPackages({
    repositoryRoot: root,
    skillNames: [definition.skillName],
  });
  return releases.at(-1);
}

function existingFiles(directory, prefix, paths) {
  let entries;

  try {
    entries = readdirSync(directory, { withFileTypes: true });
  } catch (error) {
    if (error.code === "ENOENT") {
      return;
    }

    throw error;
  }

  for (const entry of entries) {
    const published = prefix ? `${prefix}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      existingFiles(join(directory, entry.name), published, paths);
    } else {
      paths.push(published);
    }
  }
}

function syncPackage(definition, repositoryRoot, checkOnly) {
  const outputRoot = resolve(repositoryRoot, definition.outputDirectory);
  const { files } = pluginPackageFiles(definition, repositoryRoot);
  const stale = [];
  const published = [];

  existingFiles(outputRoot, "", published);

  for (const path of published) {
    if (!files.has(path)) {
      stale.push(`${definition.outputDirectory}/${path}`);

      if (!checkOnly) {
        rmSync(join(outputRoot, path));
      }
    }
  }

  for (const [path, expected] of files) {
    const destination = join(outputRoot, path);
    let committed;

    try {
      committed = readFileSync(destination);
    } catch (error) {
      if (error.code !== "ENOENT") {
        throw error;
      }
    }

    if (!committed?.equals(expected)) {
      stale.push(`${definition.outputDirectory}/${path}`);

      if (!checkOnly) {
        mkdirSync(dirname(destination), { recursive: true });
        writeFileSync(destination, expected);
      }
    }
  }

  return stale;
}

export function pluginPackageDefinition(skillName) {
  const definition = pluginPackages.find(
    (candidate) => candidate.skillName === skillName,
  );

  if (!definition) {
    throw new Error(`No host plugin package is generated for ${skillName}.`);
  }

  return definition;
}

export function buildPluginPackages({
  checkOnly = false,
  repositoryRoot = defaultRepositoryRoot,
  skillNames,
} = {}) {
  const resolvedRepositoryRoot = resolve(repositoryRoot);
  const selectedSkillNames =
    skillNames === undefined
      ? undefined
      : selectCanonicalSkillNames(
          resolve(resolvedRepositoryRoot, "skills"),
          skillNames,
        );
  const selected =
    selectedSkillNames === undefined
      ? pluginPackages
      : pluginPackages.filter((definition) =>
          selectedSkillNames.includes(definition.skillName),
        );
  const stalePackages = [];

  for (const definition of selected) {
    // In write mode every difference has just been synchronised, so only a
    // check reports them as stale.
    const changed = syncPackage(definition, resolvedRepositoryRoot, checkOnly);

    if (checkOnly) {
      stalePackages.push(...changed);
    } else {
      process.stdout.write(
        `Built ${definition.outputDirectory} (${changed.length} file(s) changed)\n`,
      );
    }
  }

  return { packagesChecked: selected.length, stalePackages };
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  try {
    const { values } = parseArgs({
      options: {
        repository: { type: "string" },
        "release-version": { type: "string" },
      },
    });
    if (!values["release-version"])
      throw new Error(
        "Usage: buildPluginPackages.js [--repository <path>] --release-version <next-version>",
      );
    const release = await advancePluginRelease({
      version: values["release-version"],
      repositoryRoot: values.repository,
    });
    process.stdout.write(`${JSON.stringify(release, null, 2)}\n`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
