import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import assert from "node:assert/strict";
import test from "node:test";

import { buildSkillArtifacts } from "../../scripts/buildSkillArtifacts.js";

const REPOSITORY_ROOT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
);
const COMMIT_WORKFLOW = join(
  REPOSITORY_ROOT,
  "skills",
  "committing-to-git",
  "scripts",
  "commitWorkflow.mjs",
);

test("artifact checks skip generated outputs owned by unrelated skills", async () => {
  const result = await buildSkillArtifacts({
    checkOnly: true,
    skillNames: ["defining-concepts"],
  });

  assert.deepEqual(result, {
    artifactsChecked: 0,
    staleArtifacts: [],
  });
});

test("artifact check accepts the committed generated outputs", async () => {
  assert.deepEqual(await buildSkillArtifacts({ checkOnly: true }), {
    artifactsChecked: 1,
    staleArtifacts: [],
  });
});

test("published commit workflow is one readable generated module", () => {
  const artifact = readFileSync(COMMIT_WORKFLOW, "utf8");

  assert.match(artifact, /Generated by scripts\/buildSkillArtifacts\.js/u);
  assert.match(
    artifact,
    /import \{ createRequire as __createRequire \} from "node:module";/u,
  );
  assert.match(
    artifact,
    /const require = __createRequire\(import\.meta\.url\);/u,
  );
  assert.match(artifact, /snapshot/u);
  assert.match(artifact, /message/u);
  assert.doesNotMatch(artifact, /sourceMappingURL/u);
  assert.ok(artifact.includes("\n"));
});
